const videoData = [
  {
    id: 1,
    title: "React Tutorial",
    category: "Education",
    views: `233K`,
    cname: "Codecamp",
    vdourl: "https://www.youtube.com/watch?v=SqcY0GlETPk",
    url: "react.jpg",
  },

  {
    id: 2,
    title: "Tenet 2022 hindi Dubbed",
    category: "Entertainment",
    views: `100M`,
    vdourl: "https://www.youtube.com/watch?v=L3pk_TBkihU",
    cname: "Universal Studios",
    url: "ten8.jpeg",
    // cname: "Abhay Karan",
  },
  {
    id: 3,
    title: "The Shawshank Redemption",
    category: "Entertainment",
    views: `65M`,
    vdourl: "https://www.youtube.com/watch?v=PLl99DlL6b4",
    url: "sock.webp",
    cname: "Sony Pictures",
  },
  {
    id: 4,
    title: "The Godfather",
    category: "Entertainment",
    views: `20M`,
    vdourl: "https://www.youtube.com/watch?v=UaVTIH8mujA",
    url: "godfather.png.webp",
    cname: "Sony Entertainment",
  },
  {
    id: 5,
    title: "JavaScript Zero to Hero 2025",
    category: "Education",
    url: "js.jpg",
    cname: "Mosh Hamedani",
  },

  {
    id: 6,
    // cname: "Abhay Karan",
    title: "Gta 5 new Trailer 2025",
    category: "Gaming",
    cname: "Rockstar gaming",
    url: "gta5.jpg",
    vdourl: "https://www.youtube.com/watch?v=xv3wFGGeIsI",
    views: "5M",
  },
  {
    id: 7,
    cname: "Scout Gaming",
    title: "Spider Man far from Office 2025",
    category: "Gaming",

    vdourl: "https://www.youtube.com/watch?v=y1kWjwVKvRA",
    views: "3.6M",
    url: "spiderman.webp",
  },
  {
    id: 8,
    cname: "Abhay Karan",
    title: "Red Dead Redemption 2 | Download",
    category: "Gaming",
    views: "1.2B",
    url: "rdr2.jpg",
  },

  {
    id: 9,
    title: "Best Veg food for Protien",
    category: "Health",
    cname: "Dr. Reddy Morgan",
    views: "2.3M",
    url: "protien.jpg",
  },
  {
    id: 10,
    cname: "Jonas Watson",
    title: "Muscle Building Excercise",
    category: "Health",
    views: "23M",
    url: "muscle.jpg",
  },
  {
    id: 11,
    cname: "Abhay Karan",
    title: "How to Boost Stamina",
    category: "Health",
    views: "1.2M",
    url: "stamina.webp",
  },

  {
    id: 12,
    cname: "Zee Music Company",
    title: " Kala Chashma | Baar Baar Dekho | Sidharth M Katrina K",
    views: "5M",
    category: "Music",
    vdourl: "https://www.youtube.com/watch?v=k4yXQkG2s1E",
    url: "kala.jpg",
  },
  {
    id: 13,
    cname: "Taylor Swift",
    title: "Taylor Swift - willow (Official Music Video)",
    category: "Music",
    views: "5B",
    vdourl: "https://www.youtube.com/watch?v=RsEZmictANA",
    url: "willo.webp",
  },
  {
    id: 14,
    cname: "Zara Larsson",
    title: "Zara Larsson - Lush Life",
    category: "Music",
    views: "4M",
    vdourl: "https://www.youtube.com/watch?v=tD4HCZe-tew",
    url: "zara.jpg",
  },
];

export default videoData;
